import Head from 'next/head'
import { useEffect, useState } from 'react';
import Advora from '../Components/Advora'
import Navbar from '../Components/Navbar'
import { getUser } from '../pages/api/edvora_api';

export default function Home() {
  const [user, setUser] = useState({});

  const getData = async () => {
    const data = await getUser();
    console.log(data);
    setUser(data);
  }
  useEffect(() => {
    getData();
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />
      <Advora station_code={user?.station_code} />
    </div>
  )
}
